// Curated habit templates for quick-start. Users can pick from these when creating a habit.
import type { HabitCreateInput } from "@/api/client";

export interface HabitTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  frequency: "daily" | "weekly" | "custom";
  customDays: number[];
  targetCount: number;
  category: string;
}

export const HABIT_TEMPLATES: HabitTemplate[] = [
  // Health & Fitness
  {
    id: "drink-water",
    name: "Drink water",
    description: "Stay hydrated throughout the day",
    icon: "💧",
    color: "#0ea5e9",
    frequency: "daily",
    customDays: [],
    targetCount: 8,
    category: "Health",
  },
  {
    id: "exercise",
    name: "Exercise",
    description: "30 minutes of physical activity",
    icon: "🏃",
    color: "#f59e0b",
    frequency: "custom",
    customDays: [0, 2, 4],
    targetCount: 1,
    category: "Health",
  },
  {
    id: "meditate",
    name: "Meditate",
    description: "10 minutes of mindfulness",
    icon: "🧘",
    color: "#10b981",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Health",
  },
  {
    id: "sleep-early",
    name: "Sleep before 11pm",
    description: "Get enough rest",
    icon: "😴",
    color: "#6366f1",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Health",
  },
  {
    id: "stretch",
    name: "Stretch",
    description: "5 minutes of stretching",
    icon: "🤸",
    color: "#14b8a6",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Health",
  },
  {
    id: "walk",
    name: "Take a walk",
    description: "10,000 steps",
    icon: "🚶",
    color: "#84cc16",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Health",
  },
  // Learning & Growth
  {
    id: "read",
    name: "Read a book",
    description: "At least 20 pages",
    icon: "📚",
    color: "#8b5cf6",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Learning",
  },
  {
    id: "learn-language",
    name: "Practice language",
    description: "15 minutes of language learning",
    icon: "🌍",
    color: "#0ea5e9",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Learning",
  },
  {
    id: "write-journal",
    name: "Write journal",
    description: "Reflect on your day",
    icon: "✍️",
    color: "#ec4899",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Learning",
  },
  {
    id: "code",
    name: "Practice coding",
    description: "Build something or learn a concept",
    icon: "💻",
    color: "#0d9488",
    frequency: "custom",
    customDays: [0, 1, 2, 3, 4],
    targetCount: 1,
    category: "Learning",
  },
  // Productivity
  {
    id: "plan-day",
    name: "Plan your day",
    description: "Set top 3 priorities each morning",
    icon: "🎯",
    color: "#10b981",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Productivity",
  },
  {
    id: "inbox-zero",
    name: "Inbox zero",
    description: "Clear your email inbox",
    icon: "📧",
    color: "#6366f1",
    frequency: "custom",
    customDays: [0, 1, 2, 3, 4],
    targetCount: 1,
    category: "Productivity",
  },
  {
    id: "deep-work",
    name: "Deep work session",
    description: "90 minutes of focused work",
    icon: "⚡",
    color: "#f59e0b",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Productivity",
  },
  {
    id: "weekly-review",
    name: "Weekly review",
    description: "Reflect on the past week",
    icon: "📋",
    color: "#ec4899",
    frequency: "weekly",
    customDays: [],
    targetCount: 1,
    category: "Productivity",
  },
  // Mindfulness & Wellness
  {
    id: "gratitude",
    name: "Practice gratitude",
    description: "Write 3 things you're grateful for",
    icon: "🙏",
    color: "#f59e0b",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Mindfulness",
  },
  {
    id: "no-phone",
    name: "Phone-free hour",
    description: "1 hour without screens",
    icon: "📵",
    color: "#ef4444",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Mindfulness",
  },
  {
    id: "outdoors",
    name: "Time outdoors",
    description: "Spend 20 minutes outside",
    icon: "🌳",
    color: "#84cc16",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Mindfulness",
  },
  // Creative
  {
    id: "creative-work",
    name: "Creative work",
    description: "Draw, write, or create something",
    icon: "🎨",
    color: "#ec4899",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Creative",
  },
  {
    id: "music-practice",
    name: "Practice instrument",
    description: "20 minutes of practice",
    icon: "🎸",
    color: "#8b5cf6",
    frequency: "custom",
    customDays: [0, 1, 2, 3, 4],
    targetCount: 1,
    category: "Creative",
  },
  // ---- Popular additions (v26) ----
  // Health
  {
    id: "no-sugar",
    name: "No added sugar",
    description: "Skip sugary snacks and drinks for the day",
    icon: "🚫",
    color: "#ef4444",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Health",
  },
  {
    id: "cold-shower",
    name: "Cold shower",
    description: "End your shower with 30 seconds of cold water",
    icon: "🚿",
    color: "#0ea5e9",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Health",
  },
  {
    id: "floss",
    name: "Floss",
    description: "Once a day, before bed",
    icon: "🦷",
    color: "#0ea5e9",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Health",
  },
  {
    id: "skincare",
    name: "Skincare routine",
    description: "Cleanse, moisturize, protect",
    icon: "🧴",
    color: "#ec4899",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Health",
  },
  {
    id: "cook-home",
    name: "Cook at home",
    description: "Prepare one meal from scratch today",
    icon: "🍳",
    color: "#f59e0b",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Health",
  },
  // Learning
  {
    id: "learn-skill",
    name: "Practice a skill",
    description: "20 minutes of deliberate practice",
    icon: "🧠",
    color: "#14b8a6",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Learning",
  },
  {
    id: "vocab",
    name: "Learn 5 new words",
    description: "Expand your vocabulary",
    icon: "📖",
    color: "#6366f1",
    frequency: "daily",
    customDays: [],
    targetCount: 5,
    category: "Learning",
  },
  // Productivity
  {
    id: "side-project",
    name: "Work on side project",
    description: "30 minutes on your own project",
    icon: "🚀",
    color: "#8b5cf6",
    frequency: "custom",
    customDays: [0, 1, 2, 3, 4],
    targetCount: 1,
    category: "Productivity",
  },
  {
    id: "pomodoro-sessions",
    name: "Pomodoro sessions",
    description: "Complete 4 focused 25-minute sessions",
    icon: "🍅",
    color: "#ef4444",
    frequency: "daily",
    customDays: [],
    targetCount: 4,
    category: "Productivity",
  },
  {
    id: "tidy-up",
    name: "Tidy workspace",
    description: "5 minutes clearing your desk at end of day",
    icon: "🧹",
    color: "#14b8a6",
    frequency: "daily",
    customDays: [],
    targetCount: 1,
    category: "Productivity",
  },
  // Mindfulness
  {
    id: "call-family",
    name: "Call family",
    description: "Check in with a loved one",
    icon: "📞",
    color: "#0ea5e9",
    frequency: "custom",
    customDays: [0, 1, 2, 3, 4],
    targetCount: 1,
    category: "Mindfulness",
  },
];

export const TEMPLATE_CATEGORIES = [
  "All",
  "Health",
  "Learning",
  "Productivity",
  "Mindfulness",
  "Creative",
] as const;

export function templateToInput(t: HabitTemplate): HabitCreateInput {
  return {
    name: t.name,
    description: t.description,
    color: t.color,
    icon: t.icon,
    frequency: t.frequency,
    customDays: t.customDays,
    targetCount: t.targetCount,
    category: t.category,
    startDate: new Date().toISOString().slice(0, 10),
  };
}
